In [2]:
%cd TRUST4

/home/pc11/TRUST4_workspace/TRUST4

In [2]:
# @markdown This cell compile the TRUST4 algorithm
!make
!echo "TRUST4 is ready to use!"

make: Nothing to be done for 'all'.
TRUST4 is ready to use!

In [3]:
!./run-trust4 -h

[Mon Jun 29 14:14:42 2026] TRUST4 v1.1.10-r633 begins.
Unknown parameter -h

In [4]:
!bash trust-example-test.sh

[Mon Jun 29 14:14:49 2026] TRUST4 v1.1.10-r633 begins.
[Mon Jun 29 14:14:49 2026] SYSTEM CALL: /home/pc11/TRUST4_workspace/TRUST4/bam-extractor -b example/example.bam -t 1 -f hg38_bcrtcr.fa -o example_test_toassemble
[Mon Jun 29 14:14:49 2026] Start to extract candidate reads from bam file.
[Mon Jun 29 14:14:49 2026] Finish obtaining the candidate read ids.
[Mon Jun 29 14:14:49 2026] Finish extracting reads.
[Mon Jun 29 14:14:49 2026] SYSTEM CALL: /home/pc11/TRUST4_workspace/TRUST4/trust4  -f hg38_bcrtcr.fa -o example_test -1 example_test_toassemble_1.fq -2 example_test_toassemble_2.fq
[Mon Jun 29 14:14:49 2026] Start to assemble reads.
[Mon Jun 29 14:14:49 2026] Found 394 reads.
[Mon Jun 29 14:14:49 2026] Finish sorting the reads.
[Mon Jun 29 14:14:49 2026] Finish rough annotations.
[Mon Jun 29 14:14:49 2026] Assembled 394 reads.
[Mon Jun 29 14:14:49 2026] Try to rescue 0 reads for assembly.
[Mon Jun 29 14:14:49 2026] Rescued 0 reads.
[Mon Jun 29 14:14:49 2026] Extend assemblies by mate pair information.
[Mon Jun 29 14:14:49 2026] Remove redundant assemblies.
[Mon Jun 29 14:14:50 2026] Finish assembly.
[Mon Jun 29 14:14:50 2026] SYSTEM CALL: /home/pc11/TRUST4_workspace/TRUST4/annotator -f human_IMGT+C.fa -a example_test_final.out -t 1 -o example_test  -r example_test_assembled_reads.fa --airrAlignment > example_test_annot.fa
[Mon Jun 29 14:14:50 2026] Start to annotate assemblies.
[Mon Jun 29 14:14:50 2026] Start to realign reads for CDR3 analysis.
[Mon Jun 29 14:14:50 2026] Compute CDR3 abundance.
[Mon Jun 29 14:14:50 2026] Finish annotation.
[Mon Jun 29 14:14:50 2026] SYSTEM CALL: perl /home/pc11/TRUST4_workspace/TRUST4/trust-simplerep.pl example_test_cdr3.out  > example_test_report.tsv
[Mon Jun 29 14:14:50 2026] SYSTEM CALL: perl /home/pc11/TRUST4_workspace/TRUST4/trust-airr.pl example_test_report.tsv example_test_annot.fa --airr-align example_test_airr_align.tsv > example_test_airr.tsv
[Mon Jun 29 14:14:50 2026] TRUST4 finishes.
Results do not match the pregenerated example results. Please check TRUST4's version or the example files are in the folder.

In [5]:
# @markdown Since this is a 10x single-cell dataset, R1 contains the cell barcode and UMI, while R2 contains the cDNA/transcript read. Therefore, TRUST4 is run as follows:

!./run-trust4 \
 -u "/home/pc11/TRUST4_workspace/SRR13342054_2.fastq" \
 -f human_IMGT+C.fa \
--ref human_IMGT+C.fa \
--barcode "/home/pc11/TRUST4_workspace/SRR13342054_1.fastq" \
--UMI "/home/pc11/TRUST4_workspace/SRR13342054_1.fastq" \
--readFormat bc:0:15,um:16:25 \
-t 4 \
-o "/home/pc11/TRUST4_workspace/SRR13342054_TRUST4"

[Mon Jun 29 14:15:45 2026] TRUST4 v1.1.10-r633 begins.
[Mon Jun 29 14:15:45 2026] SYSTEM CALL: /home/pc11/TRUST4_workspace/TRUST4/fastq-extractor -t 4 -f human_IMGT+C.fa -o /home/pc11/TRUST4_workspace/SRR13342054_TRUST4_toassemble  --readFormat bc:0:15,um:16:25 -u /home/pc11/TRUST4_workspace/SRR13342054_2.fastq --barcode /home/pc11/TRUST4_workspace/SRR13342054_1.fastq --UMI /home/pc11/TRUST4_workspace/SRR13342054_1.fastq
[Mon Jun 29 14:15:45 2026] Start to extract candidate reads from read files.
[Mon Jun 29 14:24:49 2026] Finish extracting reads.
[Mon Jun 29 14:24:49 2026] SYSTEM CALL: /home/pc11/TRUST4_workspace/TRUST4/trust4  -t 4 -f human_IMGT+C.fa -o /home/pc11/TRUST4_workspace/SRR13342054_TRUST4 -u /home/pc11/TRUST4_workspace/SRR13342054_TRUST4_toassemble.fq --barcode /home/pc11/TRUST4_workspace/SRR13342054_TRUST4_toassemble_bc.fa --UMI /home/pc11/TRUST4_workspace/SRR13342054_TRUST4_toassemble_umi.fa
[Mon Jun 29 14:24:50 2026] Start to assemble reads.
[Mon Jun 29 14:24:54 2026] Found 243994 reads.
[Mon Jun 29 14:24:55 2026] Finish sorting the reads.
[Mon Jun 29 14:24:59 2026] Finish rough annotations.
[Mon Jun 29 14:24:59 2026] Get barcode-wise kmer count.
[Mon Jun 29 14:25:01 2026] Finish barcode-wise kmer count.
[Mon Jun 29 14:25:01 2026] Finish re-sorting the reads based on barcode.
[Mon Jun 29 14:25:02 2026] Processed 100000 reads (69532 are used for assembly).
[Mon Jun 29 14:25:03 2026] Processed 200000 reads (136523 are used for assembly).
[Mon Jun 29 14:25:04 2026] Assembled 158947 reads.
[Mon Jun 29 14:25:04 2026] Try to rescue 746 reads for assembly.
[Mon Jun 29 14:25:04 2026] Rescued 7 reads.
[Mon Jun 29 14:25:06 2026] SYSTEM CALL: /home/pc11/TRUST4_workspace/TRUST4/annotator -f human_IMGT+C.fa -a /home/pc11/TRUST4_workspace/SRR13342054_TRUST4_final.out -t 4 -o /home/pc11/TRUST4_workspace/SRR13342054_TRUST4  --barcode --UMI -r /home/pc11/TRUST4_workspace/SRR13342054_TRUST4_assembled_reads.fa --airrAlignment > /home/pc11/TRUST4_workspace/SRR13342054_TRUST4_annot.fa
[Mon Jun 29 14:25:06 2026] Start to annotate assemblies.
[Mon Jun 29 14:25:12 2026] Start to realign reads for CDR3 analysis.
[Mon Jun 29 14:25:14 2026] Compute CDR3 abundance.
[Mon Jun 29 14:25:14 2026] Finish annotation.
[Mon Jun 29 14:25:15 2026] SYSTEM CALL: perl /home/pc11/TRUST4_workspace/TRUST4/trust-barcoderep.pl /home/pc11/TRUST4_workspace/SRR13342054_TRUST4_cdr3.out -a /home/pc11/TRUST4_workspace/SRR13342054_TRUST4_annot.fa --chainsInBarcode 2 > /home/pc11/TRUST4_workspace/SRR13342054_TRUST4_barcode_report.tsv
[Mon Jun 29 14:25:15 2026] SYSTEM CALL: perl /home/pc11/TRUST4_workspace/TRUST4/trust-simplerep.pl /home/pc11/TRUST4_workspace/SRR13342054_TRUST4_cdr3.out  --barcodeCnt --filterBarcoderep /home/pc11/TRUST4_workspace/SRR13342054_TRUST4_barcode_report.tsv > /home/pc11/TRUST4_workspace/SRR13342054_TRUST4_report.tsv
[Mon Jun 29 14:25:15 2026] SYSTEM CALL: perl /home/pc11/TRUST4_workspace/TRUST4/trust-airr.pl /home/pc11/TRUST4_workspace/SRR13342054_TRUST4_report.tsv /home/pc11/TRUST4_workspace/SRR13342054_TRUST4_annot.fa --airr-align /home/pc11/TRUST4_workspace/SRR13342054_TRUST4_airr_align.tsv > /home/pc11/TRUST4_workspace/SRR13342054_TRUST4_airr.tsv
[Mon Jun 29 14:25:16 2026] SYSTEM CALL: perl /home/pc11/TRUST4_workspace/TRUST4/trust-airr.pl /home/pc11/TRUST4_workspace/SRR13342054_TRUST4_barcode_report.tsv /home/pc11/TRUST4_workspace/SRR13342054_TRUST4_annot.fa --format barcoderep --airr-align /home/pc11/TRUST4_workspace/SRR13342054_TRUST4_airr_align.tsv > /home/pc11/TRUST4_workspace/SRR13342054_TRUST4_barcode_airr.tsv
[Mon Jun 29 14:25:16 2026] TRUST4 finishes.

In [2]:
!pip install pandas

/usr/bin/sh: 1: pip: not found

In [4]:

import pandas as pd

# Path to the TRUST4 barcode report file
trust_path = "/home/pc11/TRUST4_workspace/SRR13342054_TRUST4_barcode_report.tsv"

# Output CSV file path for paired clonotypes
out_path = "/home/pc11/TRUST4_workspace/trust4_paired_all_clonotypes.csv"

# Load the barcode report
trust = pd.read_csv(trust_path, sep="\t")

print(f"Total barcode rows in TRUST4 output: {trust.shape[0]}")


def parse_chain(chain_value, chain_type):
    """
    Parses the TRUST4 chain format:
    V,D,J,C,CDR3nt,CDR3aa,count,contig_id,score,flag

    chain1 = typically TRB (beta)
    chain2 = typically TRA (alpha)

    Allele information and '*' symbols are preserved.
    """
    if pd.isna(chain_value) or str(chain_value).strip() == "*":
        return None

    parts = str(chain_value).split(",")

    # Ensure we have at least up to CDR3aa
    if len(parts) < 6:
        return None

    return {
        "chain": chain_type,
        "v_gene": parts[0],
        "d_gene": parts[1],
        "j_gene": parts[2],
        "c_gene": parts[3],
        "cdr3_nt": parts[4],
        "cdr3": parts[5]
    }

Total barcode rows in TRUST4 output: 949

In [5]:
paired_cells = []

for _, row in trust.iterrows():
    # Get the raw barcode string
    barcode_clean = str(row["#barcode"])

    # Parse chain1 as beta (TRB) and chain2 as alpha (TRA)
    beta = parse_chain(row["chain1"], "TRB")
    alpha = parse_chain(row["chain2"], "TRA")

    # Keep only cells that have both beta and alpha chains
    if beta is None or alpha is None:
        continue

    # A chain is 'complete' if it has valid V, J, and CDR3 sequences
    beta_complete = (
        beta["v_gene"] != "*"
        and beta["j_gene"] != "*"
        and beta["cdr3"] not in ["", "*"]
    )

    alpha_complete = (
        alpha["v_gene"] != "*"
        and alpha["j_gene"] != "*"
        and alpha["cdr3"] not in ["", "*"]
    )

    if not beta_complete or not alpha_complete:
        continue

    # Create unique keys for the beta and alpha chains
    beta_key = f"{beta['v_gene']}_{beta['j_gene']}_{beta['cdr3']}"
    alpha_key = f"{alpha['v_gene']}_{alpha['j_gene']}_{alpha['cdr3']}"

    # Create the paired key (the combination of both chains)
    paired_key = f"TRB={beta_key}|TRA={alpha_key}"

    paired_cells.append({
        "barcode_clean": barcode_clean,
        "paired_key": paired_key,
        "beta": beta,
        "alpha": alpha
    })

paired = pd.DataFrame(paired_cells)

if paired.empty:
    raise ValueError("Could not find any suitable barcodes with complete paired TRA-TRB chains.")

print(f"Number of unique barcodes with complete paired TRA-TRB: {paired['barcode_clean'].nunique()}")

Number of unique barcodes with complete paired TRA-TRB: 224

In [6]:
# Count how many unique barcodes share each paired clonotype
clone_sizes = (
    paired.groupby("paired_key")["barcode_clean"]
    .nunique()
    .reset_index(name="clone_size")
    .sort_values(["clone_size", "paired_key"], ascending=[False, True])
    .reset_index(drop=True)
)

# Generate a Clonotype ID starting from the largest clone
clone_sizes["raw_clonotype_id"] = [f"clonotype{i + 1}" for i in range(clone_sizes.shape[0])]

# Merge the Clonotype ID and clone size back into the main cell dataframe
paired = paired.merge(
    clone_sizes[["paired_key", "raw_clonotype_id", "clone_size"]],
    on="paired_key",
    how="left"
)

In [7]:
# Create a long-format table similar to standard experimental VDJ outputs
output_rows = []

for _, row in paired.iterrows():
    barcode_clean = row["barcode_clean"]
    # Append '-1' to match standard 10x barcode formats if needed
    barcode = f"{barcode_clean}-1"

    beta = row["beta"]
    alpha = row["alpha"]

    # First, append the TRB (beta) chain row
    output_rows.append({
        "barcode": barcode,
        "barcode_clean": barcode_clean,
        "raw_clonotype_id": row["raw_clonotype_id"],
        "chain": "TRB",
        "v_gene": beta["v_gene"],
        "d_gene": beta["d_gene"],
        "j_gene": beta["j_gene"],
        "c_gene": beta["c_gene"],
        "cdr3": beta["cdr3"],
        "cdr3_nt": beta["cdr3_nt"],
        "clone_size": row["clone_size"]
    })

    # Next, append the TRA (alpha) chain row for the same cell
    output_rows.append({
        "barcode": barcode,
        "barcode_clean": barcode_clean,
        "raw_clonotype_id": row["raw_clonotype_id"],
        "chain": "TRA",
        "v_gene": alpha["v_gene"],
        "d_gene": alpha["d_gene"],
        "j_gene": alpha["j_gene"],
        "c_gene": alpha["c_gene"],
        "cdr3": alpha["cdr3"],
        "cdr3_nt": alpha["cdr3_nt"],
        "clone_size": row["clone_size"]
    })

trust_paired = pd.DataFrame(output_rows)

# Extract the numeric part of the clonotype ID for proper sorting
trust_paired["clonotype_number"] = (
    trust_paired["raw_clonotype_id"]
    .str.replace("clonotype", "", regex=False)
    .astype(int)
)

# Order chains: TRB first, then TRA for a given barcode
chain_order = {"TRB": 1, "TRA": 2}
trust_paired["chain_order"] = trust_paired["chain"].map(chain_order)

# Sort the final dataframe:
# 1. Largest clones first
# 2. Clonotype ID number
# 3. Barcode sequence
# 4. TRB then TRA
trust_paired = trust_paired.sort_values(
    ["clone_size", "clonotype_number", "barcode_clean", "chain_order"],
    ascending=[False, True, True, True]
)

# Drop helper columns
trust_paired = trust_paired.drop(columns=["clonotype_number", "chain_order"])

# Save to CSV
trust_paired.to_csv(out_path, index=False)

# Print Summary Statistics
print(f"\nTotal paired clonotypes found: {clone_sizes.shape[0]}")
print("\nTop 20 paired clonotypes:")
print(clone_sizes[["raw_clonotype_id", "clone_size", "paired_key"]].head(20))

print("\nFirst 30 rows of output data:")
display(trust_paired.head(30))

print(f"\nOutput saved successfully to:\n{out_path}")

Total paired clonotypes found: 193

Top 20 paired clonotypes:
   raw_clonotype_id  clone_size  \
0        clonotype1           4
1        clonotype2           3
2        clonotype3           3
3        clonotype4           3
4        clonotype5           3
5        clonotype6           3
6        clonotype7           3
7        clonotype8           2
8        clonotype9           2
9       clonotype10           2
10      clonotype11           2
11      clonotype12           2
12      clonotype13           2
13      clonotype14           2
14      clonotype15           2
15      clonotype16           2
16      clonotype17           2
17      clonotype18           2
18      clonotype19           2
19      clonotype20           2

                                           paired_key
0   TRB=TRBV5-1*01_TRBJ1-1*01_CASSLARDTEAFF|TRA=TR...
1   TRB=TRBV20-1*01_TRBJ2-7*01_CSARDVRVYEQYF|TRA=T...
2   TRB=TRBV20-1*02_TRBJ2-1*01_CSAIPFKLQSGRSYNEQFF...
3   TRB=TRBV28*01_TRBJ2-7*01_CATHYNYEQYF|TRA=TRAV1...
4   TRB=TRBV7-2*01_TRBJ1-3*01_CASSLVDGNTIYF|TRA=TR...
5   TRB=TRBV7-3*01_TRBJ2-1*01_CASRPEGYNEQFF|TRA=TR...
6   TRB=TRBV9*01_TRBJ1-1*01_CASSVGGTGSTEAFF|TRA=TR...
7   TRB=TRBV10-2*01_TRBJ1-2*01_CASSELHLYGYTF|TRA=T...
8   TRB=TRBV11-2*01_TRBJ2-1*01_CASSLEALADYNEQFF|TR...
9   TRB=TRBV12-4*01_TRBJ1-1*01_CASSGSGTGNTEAFF|TRA...
10  TRB=TRBV2*01_TRBJ1-1*01_CASRTDRVEAFF|TRA=TRAV2...
11  TRB=TRBV20-1*01_TRBJ2-7*01_CSAAGFYEQYF|TRA=TRA...
12  TRB=TRBV20-1*02_TRBJ1-2*01_CSATSGRETGGYTF|TRA=...
13  TRB=TRBV20-1*02_TRBJ1-5*01_CSARGTGGDQPQHF|TRA=...
14  TRB=TRBV20-1*02_TRBJ2-1*01_CSAIPFKLQSGRSYNEQFF...
15  TRB=TRBV28*01_TRBJ2-7*01_CASSLVPQRENEQYF|TRA=T...
16  TRB=TRBV3-1*01_TRBJ2-1*01_CASSNFGTPGSQFF|TRA=T...
17  TRB=TRBV4-1*01_TRBJ1-4*01_CASSQDSGRGGLFF|TRA=T...
18  TRB=TRBV5-5*02_TRBJ2-7*01_CASSSLVQGASYEQYF|TRA...
19  TRB=TRBV6-1*01_TRBJ1-1*01_CASKRDFQRAFF|TRA=TRA...

First 30 rows of output data:

,barcode,barcode_clean,raw_clonotype_id,chain,v_gene,d_gene,j_gene,c_gene,cdr3,cdr3_nt,clone_size
202,ACATCAGAGATATGGT-1,ACATCAGAGATATGGT,clonotype1,TRB,TRBV5-1*01,TRBD1*01,TRBJ1-1*01,*,CASSLARDTEAFF,TGCGCCAGCAGCTTGGCCAGGGACACTGAAGCTTTCTTT,4
203,ACATCAGAGATATGGT-1,ACATCAGAGATATGGT,clonotype1,TRA,TRAV25*01,*,TRAJ52*01,TRAC,CAACNAGGTSYGKLTF,TGTGCAGCTTGTAATGCTGGTGGTACTAGCTATGGAAAGCTGACATTT,4
22,AGCAGCCCATCGGTTA-1,AGCAGCCCATCGGTTA,clonotype1,TRB,TRBV5-1*01,TRBD1*01,TRBJ1-1*01,TRBC1,CASSLARDTEAFF,TGCGCCAGCAGCTTGGCCAGGGACACTGAAGCTTTCTTT,4
23,AGCAGCCCATCGGTTA-1,AGCAGCCCATCGGTTA,clonotype1,TRA,TRAV25*01,*,TRAJ52*01,*,CAACNAGGTSYGKLTF,TGTGCAGCTTGTAATGCTGGTGGTACTAGCTATGGAAAGCTGACATTT,4
42,CAGAATCCACTTAACG-1,CAGAATCCACTTAACG,clonotype1,TRB,TRBV5-1*01,TRBD1*01,TRBJ1-1*01,TRBC1,CASSLARDTEAFF,TGCGCCAGCAGCTTGGCCAGGGACACTGAAGCTTTCTTT,4
43,CAGAATCCACTTAACG-1,CAGAATCCACTTAACG,clonotype1,TRA,TRAV25*01,*,TRAJ52*01,TRAC,CAACNAGGTSYGKLTF,TGTGCAGCTTGTAATGCTGGTGGTACTAGCTATGGAAAGCTGACATTT,4
410,TACCTTATCCGTTGTC-1,TACCTTATCCGTTGTC,clonotype1,TRB,TRBV5-1*01,TRBD1*01,TRBJ1-1*01,TRBC1,CASSLARDTEAFF,TGCGCCAGCAGCTTGGCCAGGGACACTGAAGCTTTCTTT,4
411,TACCTTATCCGTTGTC-1,TACCTTATCCGTTGTC,clonotype1,TRA,TRAV25*01,*,TRAJ52*01,*,CAACNAGGTSYGKLTF,TGTGCAGCTTGTAATGCTGGTGGTACTAGCTATGGAAAGCTGACATTT,4
430,CAGAGAGTCAAGGCTT-1,CAGAGAGTCAAGGCTT,clonotype2,TRB,TRBV20-1*01,TRBD1*01,TRBJ2-7*01,TRBC2,CSARDVRVYEQYF,TGCAGTGCTAGAGATGTCAGGGTCTACGAGCAGTACTTC,3
431,CAGAGAGTCAAGGCTT-1,CAGAGAGTCAAGGCTT,clonotype2,TRA,TRAV26-1*01,*,TRAJ22*01,TRAC,CIVRVAGSARQLTF,TGCATCGTCAGAGTCGCCGGTTCTGCAAGGCAACTGACCTTT,3
384,CTAATGGAGTCTCAAC-1,CTAATGGAGTCTCAAC,clonotype2,TRB,TRBV20-1*01,TRBD1*01,TRBJ2-7*01,TRBC2,CSARDVRVYEQYF,TGCAGTGCTAGAGATGTCAGGGTCTACGAGCAGTACTTC,3
385,CTAATGGAGTCTCAAC-1,CTAATGGAGTCTCAAC,clonotype2,TRA,TRAV26-1*01,*,TRAJ22*01,TRAC,CIVRVAGSARQLTF,TGCATCGTCAGAGTCGCCGGTTCTGCAAGGCAACTGACCTTT,3
58,GTAGTCACAGTCGTGC-1,GTAGTCACAGTCGTGC,clonotype2,TRB,TRBV20-1*01,TRBD1*01,TRBJ2-7*01,TRBC2,CSARDVRVYEQYF,TGCAGTGCTAGAGATGTCAGGGTCTACGAGCAGTACTTC,3
59,GTAGTCACAGTCGTGC-1,GTAGTCACAGTCGTGC,clonotype2,TRA,TRAV26-1*01,*,TRAJ22*01,TRAC,CIVRVAGSARQLTF,TGCATCGTCAGAGTCGCCGGTTCTGCAAGGCAACTGACCTTT,3
276,AGGCCACGTCTTGATG-1,AGGCCACGTCTTGATG,clonotype3,TRB,TRBV20-1*02,TRBD2*02,TRBJ2-1*01,TRBC1,CSAIPFKLQSGRSYNEQFF,TGCAGTGCTATCCCCTTTAAACTTCAAAGCGGGAGGTCCTACAATG...,3
277,AGGCCACGTCTTGATG-1,AGGCCACGTCTTGATG,clonotype3,TRA,TRAV39*01,*,TRAJ45*01,*,CAVEETGGGADGLTF,TGTGCCGTGGAAGAGACAGGAGGAGGTGCTGACGGACTCACCTTT,3
252,GTCCTCATCGTGGACC-1,GTCCTCATCGTGGACC,clonotype3,TRB,TRBV20-1*02,TRBD2*02,TRBJ2-1*01,TRBC2,CSAIPFKLQSGRSYNEQFF,TGCAGTGCTATCCCCTTTAAACTTCAAAGCGGGAGGTCCTACAATG...,3
253,GTCCTCATCGTGGACC-1,GTCCTCATCGTGGACC,clonotype3,TRA,TRAV39*01,*,TRAJ45*01,*,CAVEETGGGADGLTF,TGTGCCGTTGAAGAGACAGGAGGAGGTGCTGACGGACTCACCTTT,3
390,TGAGCATTCTGGTATG-1,TGAGCATTCTGGTATG,clonotype3,TRB,TRBV20-1*02,TRBD2*02,TRBJ2-1*01,*,CSAIPFKLQSGRSYNEQFF,TGCAGTGCTATCCCCTTTAAACTTCAAAGCGGGAGGTCCTACAATG...,3
391,TGAGCATTCTGGTATG-1,TGAGCATTCTGGTATG,clonotype3,TRA,TRAV39*01,*,TRAJ45*01,TRAC,CAVEETGGGADGLTF,TGTGCCGTGGAAGAGACAGGAGGAGGTGCTGACGGACTCACCTTT,3
398,CATCCACAGCACACAG-1,CATCCACAGCACACAG,clonotype4,TRB,TRBV28*01,*,TRBJ2-7*01,TRBC2,CATHYNYEQYF,TGTGCCACCCATTACAACTACGAGCAGTACTTC,3
399,CATCCACAGCACACAG-1,CATCCACAGCACACAG,clonotype4,TRA,TRAV14/DV4*02,*,TRAJ28*01,*,CAMRPGTGAGSYQLTF,TGTGCAATGAGGCCAGGGACTGGGGCTGGGAGTTACCAACTCACTTTC,3
368,GGACATTCACCATGTA-1,GGACATTCACCATGTA,clonotype4,TRB,TRBV28*01,*,TRBJ2-7*01,TRBC2,CATHYNYEQYF,TGTGCCACCCATTACAACTACGAGCAGTACTTC,3
369,GGACATTCACCATGTA-1,GGACATTCACCATGTA,clonotype4,TRA,TRAV14/DV4*02,*,TRAJ28*01,*,CAMRPGTGAGSYQLTF,TGTGCAATGAGGCCAGGGACTGGGGCTGGGAGTTACCAACTCACTTTC,3
232,TCATTACTCAATCACG-1,TCATTACTCAATCACG,clonotype4,TRB,TRBV28*01,*,TRBJ2-7*01,TRBC2,CATHYNYEQYF,TGTGCCACCCATTACAACTACGAGCAGTACTTC,3
233,TCATTACTCAATCACG-1,TCATTACTCAATCACG,clonotype4,TRA,TRAV14/DV4*02,*,TRAJ28*01,*,CAMRPGTGAGSYQLTF,TGTGCAATGAGGCCAGGGACTGGGGCTGGGAGTTACCAACTCACTTTC,3
326,AACCATGCACACCGAC-1,AACCATGCACACCGAC,clonotype5,TRB,TRBV7-2*01,*,TRBJ1-3*01,TRBC1,CASSLVDGNTIYF,TGTGCCAGCAGCTTAGTGGACGGAAACACCATATATTTT,3
327,AACCATGCACACCGAC-1,AACCATGCACACCGAC,clonotype5,TRA,TRAV29/DV5*01,*,TRAJ39*01,*,CAATCEAGNMLTF,TGTGCAGCAACCTGCGAGGCAGGCAACATGCTCACCTTT,3
394,AGCGTCGCATTCTCAT-1,AGCGTCGCATTCTCAT,clonotype5,TRB,TRBV7-2*01,*,TRBJ1-3*01,TRBC1,CASSLVDGNTIYF,TGTGCCAGCAGCTTAGTGGACGGAAACACCATATATTTT,3
395,AGCGTCGCATTCTCAT-1,AGCGTCGCATTCTCAT,clonotype5,TRA,TRAV29/DV5*01,*,TRAJ39*01,*,CAATCEAGNMLTF,TGTGCAGCAACCTGCGAGGCAGGCAACATGCTCACCTTT,3

Output saved successfully to:
/home/pc11/TRUST4_workspace/trust4_paired_all_clonotypes.csv

In [8]:
import pandas as pd

# Load TRUST4 barcode report
trust4_report = pd.read_csv(
    "/home/pc11/TRUST4_workspace/SRR13342054_TRUST4_barcode_report.tsv",
    sep="\t"
)

print(f"📊 Total cells with TCR/BCR: {len(trust4_report)}")
print(f"📊 Columns: {list(trust4_report.columns)}")
print(f"\n🔍 First 5 rows:")
trust4_report.head()

📊 Total cells with TCR/BCR: 949
📊 Columns: ['#barcode', 'cell_type', 'chain1', 'chain2', 'secondary_chain1', 'secondary_chain2']

🔍 First 5 rows:

,#barcode,cell_type,chain1,chain2,secondary_chain1,secondary_chain2
0,GACGTGCAGGCGATAC,abT,"TRBV7-3*01,TRBD2*01,TRBJ1-2*01,TRBC1,TGTGCCAGC...","TRAV4*01,*,TRAJ42*01,*,GGCCTCGTGGGTGATTATGTAGG...","TRBV29-1*01,TRBD2*02,TRBJ2-3*01,*,TGCAGCGTTGAA...","TRAV9-2*03,*,TRAJ32*02,*,TGTGCTCTGACCGCGGGGGTG..."
1,CAGCTGGCAAGCGATG,abT,"TRBV5-5*02,TRBD1*01,TRBJ1-1*01,TRBC1,TGTGCCAGC...",*,*,*
2,TGCGTGGAGTACGATA,abT,"TRBV7-3*01,*,TRBJ2-1*01,*,TGTGCCAGCAGGCCTGAAGG...",*,*,*
3,AGTGGGAGTGAGGCTA,abT,"TRBV2*01,TRBD1*01,TRBJ1-1*01,*,TGTGCCAGCAGATTA...",*,*,*
4,CATCGAAAGACACGAC,abT,*,"TRAV26-2*01,*,TRAJ29*01,*,TGCATCCTGAGACGGAATTC...",*,*

In [9]:
# Count cell types detected by TRUST4
if 'cell_type' in trust4_report.columns:
    print("🧬 Cell type distribution from TRUST4:")
    print(trust4_report['cell_type'].value_counts())
    print(f"\n📊 Total cells with immune receptors: {len(trust4_report)}")

🧬 Cell type distribution from TRUST4:
cell_type
abT    918
B       22
gdT      9
Name: count, dtype: int64

📊 Total cells with immune receptors: 949